### PR TITLE
Bug 1611: Name server labels

### LINKED ISSUE #1611: During deletions, nameserver records have misleading label of "optional" while it is evaluated as required
### Current Behavior

On nameservers, if you delete the first or second record, the server label will say 'optional' while it is marked and validated as required. 

### Expected Behavior

On nameserver record deletions, the server label should NOT say 'optional' when it is marked and validated as required.

### Steps to Reproduce

1.

### Environment

Stable

### Additional Context

_No response_

### Issue Links

_No response_

### PR DESCRIPTION
**Pull request by rachidatecs**
## Ticket

Resolves #1611 

## Changes

- Account in JS for the backend added '(optional)' when adding or removing forms in the formset
- Copy edits on other contacts page (@Katherine-Osos) 

## Context for reviewers

Delete one of the first 2 name servers. The word 'optional' does not show on the label of the name server that comes to replace the deleted one. Add name servers, the word optional is present on the newly created forms. 

#### Satisfied acceptance criteria and met development standards

- [x] Met the acceptance criteria, or will meet them in a subsequent PR
- [ ] Created/modified automated tests
- [x] Added at least 2 developers as PR reviewers (only 1 will need to approve)
- [x] Messaged on Slack or in standup to notify the team that a PR is ready for review
- [ ] Changes to “how we do things” are documented in READMEs and or onboarding guide
- [ ] If any model was updated to modify/add/delete columns, makemigrations was ran and the assoicated migrations file has been commited.

#### Ensured code standards are met (Original Developer)

- [x] All new functions and methods are commented using plain language
- [ ] Did dependency updates in Pipfile also get changed in requirements.txt?
- [ ] Interactions with external systems are wrapped in try/except
- [ ] Error handling exists for unusual or missing values

#### Validated user-facing changes (if applicable)

- [ ] New pages have been added to .pa11yci file so that they will be tested with our automated accessibility testing
- [ ] Checked keyboard navigability
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)
- [ ] Add at least 1 designer as PR reviewer

#### Reviewed, tested, and left feedback about the changes

- [ ] Pulled this branch locally and tested it
- [ ] Reviewed this code and left comments
- [ ] Checked that all code is adequately covered by tests
- [ ] Made it clear which comments need to be addressed before this work is merged
- [ ] If any model was updated to modify/add/delete columns, makemigrations was ran and the assoicated migrations file has been commited.

#### Ensured code standards are met (Code reviewer)

- [ ] All new functions and methods are commented using plain language
- [ ] Interactions with external systems are wrapped in try/except
- [ ] Error handling exists for unusual or missing values
- [ ] (Rarely needed) Did dependency updates in Pipfile also get changed in requirements.txt?

#### Validated user-facing changes as a developer

- [ ] New pages have been added to .pa11yci file so that they will be tested with our automated accessibility testing
- [ ] Checked keyboard navigability
- [ ] Meets all designs and user flows provided by design/product
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)

- [ ] Tested with multiple browsers, the suggestion is to use ones that the developer didn't (check off which ones were used)
  - [ ] Chrome
  - [ ] Microsoft Edge
  - [ ] FireFox
  - [ ] Safari

- [ ] (Rarely needed) Tested as both an analyst and applicant user

**Note:** Multiple code reviewers can share the checklists above, a second reviewers should not make a duplicate checklist

#### Verified that the changes match the design intention

- [ ] Checked that the design translated visually
- [ ] Checked behavior
- [ ] Checked different states (empty, one, some, error)
- [ ] Checked for landmarks, page heading structure, and links
- [ ] Tried to break the intended flow

#### Validated user-facing changes as a designer

- [ ] Checked keyboard navigability
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)

- [ ] Tested with multiple browsers (check off which ones were used)
  - [ ] Chrome
  - [ ] Microsoft Edge
  - [ ] FireFox
  - [ ] Safari

- [ ] (Rarely needed) Tested as both an analyst and applicant user

### CODE REVIEW

**Review by Katherine-Osos — APPROVED** [review]

**Comment by Katherine-Osos** [comment]
LGTM!

File: src/registrar/assets/js/get-gov.js [hunk 1]
```diff
@@ -260,10 +260,22 @@ function removeForm(e, formLabel, isNameserversForm, addButton, formIdentifier){
...
     // h2 and legend for DS form, label for nameservers  
     Array.from(form.querySelectorAll('h2, legend, label, p')).forEach((node) => {
+
+      let innerSpan = node.querySelector('span')
+      if (innerSpan) {
+        innerSpan.textContent = innerSpan.textContent.replace(formLabelRegex, `${formLabel} ${index + 1}`);
+      } else {
+        node.textContent = node.textContent.replace(formLabelRegex, `${formLabel} ${index + 1}`);
+        node.textContent = node.textContent.replace(formExampleRegex, `ns${index + 1}`);
+      }
```
Comment (zandercymatics) [inline src/registrar/assets/js/get-gov.js:270]: (Q) Why was this moved?

File: src/registrar/assets/js/get-gov.js [hunk 2]
```diff
@@ -512,16 +519,24 @@ function hideDeletedForms() {
...
       } else {
-        newForm.innerHTML = newForm.innerHTML.replace(formLabelRegex, `${formLabel} ${formNum}`);
+        // Nameservers form is cloned from index 2 which has the word optional on init, does not have the word optional
+        // if indices 0 or 1 have been deleted
+        let containsOptional = newForm.innerHTML.includes('(optional)');
+        if (isNameserversForm && !containsOptional) {
+          newForm.innerHTML = newForm.innerHTML.replace(formLabelRegex, `${formLabel} ${formNum} (optional)`);
+        } else {
+          newForm.innerHTML = newForm.innerHTML.replace(formLabelRegex, `${formLabel} ${formNum}`);
+        }
```
Comment (zandercymatics) [inline src/registrar/assets/js/get-gov.js:535]: (Optional) I think there may an existing override on the backend (get_form?) that you may be able to use to make some of these checks a bit easier. Rather than check for the word optional, consider adding some sort of toggleable tag (like isOptional or even a class) to the html content on init (or within the JS init).

Then you can add a function which checks for this tag and does some work on the formLabel if its found (plus maybe toggling the bool). For example,
```
if form.isOptional:
newForm.innerHTML = newForm.innerHTML.replace(formLabelRegex, `${formLabel} ${formNum} (optional)`);
else: 
newForm.innerHTML = newForm.innerHTML.replace(formLabelRegex, `${formLabel} ${formNum}`);
```
That way, this 'function' could be reused in both areas and it simplifies the logic flow
image

**Review by zandercymatics — APPROVED** [review]
LGTM. Tested on backup and it works as you'd expect. Code looks good too

**Review by therealslimhsiehdy — APPROVED** [review]
LGTM testing wise! Also to my best knowledge of js I seems to look good as well, but will default to others for if there's any styling suggestions
